name: 🔄 Check Updates

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  workflow_dispatch:


jobs:
  check_updates:
    name: Check for updates
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.version.outputs.latest }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: Build & Check for updates
        id: version
        run: |
          go build -o version-updater version-updater.go
          chmod +x ./version-updater
          echo "latest=$(./version-updater)" >> $GITHUB_OUTPUT

      - name: Summary
        run: echo "### 🚀 Latest Version - ${{ steps.version.outputs.latest }}" >> $GITHUB_STEP_SUMMARY


