name: 🔄 Check Updates

on:
  schedule:
    - cron:  '0 0 * * *' # Every day at midnight

jobs:
  check_updates:
    name: Check for updates
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.version.outputs.latest }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: Build version-updater
        run: |
          go build -o version-updater version-updater.go

      - name: Check for updates
        id: version
        run: |
          chmod +x ./version-updater
          echo "latest=$(./version-updater)" >> $GITHUB_OUTPUT
      
