name: 🔄 Check Updates

on:
  schedule:
    - cron: '0 20 * * 6' # At 20:00 on Saturday
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_updates:
  # Checks for updates to Burp Suite, by compiling the version-updater.go file and running it.
  # If there is a newer version, it will update the BURP_VERSION file and commit the changes.
  # Also, it will generate a new README.md file with the new version number and URLs.
  # Finally, it will upload the latest version number and a boolean indicating if there were changes to the 'updates' artifact.
    name: Check for updates
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.version.outputs.latest }}
      changes_detected: ${{ steps.version.outputs.changes_detected }}
      commit_hash: ${{ steps.commit.outputs.commit_hash }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@latest
        with:
          envFilePath: .github/variables/global.env

      - name: Get latest release from GitHub
        id: last_release
        uses: InsonusK/get-latest-release@v1.1.0
        with:
          myToken: ${{ github.token }}
          view_top: 1

      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.2

      - name: Build & Check for updates
        id: version
        run: |
          go build -o version-updater version-updater.go
          chmod +x ./version-updater
          lastversion=$(echo -n ${{ steps.last_release.outputs.tag_name }})
          version=$(./version-updater)
          echo "latest=$version" >> $GITHUB_OUTPUT
          echo "Updated version hashes: $lastversion to $version"
          if [ "$lastversion" != "$version" ]; then
            echo "### 🚀 New Version - $version" >> $GITHUB_STEP_SUMMARY
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "### Up to date! ($version)" >> $GITHUB_STEP_SUMMARY
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

  create_release:
    # Creates a new release if there were changes detected in the previous job.
    # It will also upload the Burp Suite JAR file to the release.
    name: Create Release
    needs: check_updates
    if: needs.check_updates.outputs.changes_detected == 'true'
    secrets: inherit
    with:
      version: ${{ needs.check_updates.outputs.latest }}
      commit_hash: ${{ needs.check_updates.outputs.commit_hash }}
    uses: mmgordon82/BurpSuiteInstaller/.github/workflows/release.yml@main