name: 🔄 Check Updates

on:
  schedule:
    - cron: '0 20 * * *' # Every day at 20:00
  workflow_dispatch:


env:
  BURP_VERSION_FILE: BURP_VERSION

permissions:
  contents: write

jobs:
  check_updates:
    name: Check for updates
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.version.outputs.latest }}
      changes_detected: ${{ steps.version.outputs.changes_detected }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: Build & Check for updates
        id: version
        run: |
          go build -o version-updater version-updater.go
          chmod +x ./version-updater
          currenthash=$(md5sum $BURP_VERSION_FILE | cut -d ' ' -f 1)
          ./version-updater > $BURP_VERSION_FILE
          rm -f ./version-updater
          version=$(cat ${{ env.BURP_VERSION_FILE }})
          echo "latest=$version" >> $GITHUB_OUTPUT
          latesthash=$(md5sum $BURP_VERSION_FILE | cut -d ' ' -f 1)
          echo "Updated version hashes: $currenthash to $latesthash"
          if [ "$currenthash" != "$latesthash" ]; then
            echo "### 🚀 New Version - $version" >> $GITHUB_STEP_SUMMARY
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "### Up to date! ($version)" >> $GITHUB_STEP_SUMMARY
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Check Changes
        if: ${{ steps.version.outputs.changes_detected == 'true' }}
        run: |
          echo "Changes detected!"
          echo "Latest version: ${{ steps.version.outputs.latest }}"
          echo "Changes detected: ${{ steps.version.outputs.changes_detected }}"
          cat ${{ env.BURP_VERSION_FILE }}

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[AUTO] Update Burp Version"
