name: 🔄 Check Updates

on:
  schedule:
    - cron: '0 20 * * 6' # At 20:00 on Saturday
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_updates:
    name: Check for updates
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.version.outputs.latest }}
      changes_detected: ${{ steps.version.outputs.changes_detected }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@latest
        with:
          envFilePath: .github/variables/global.env

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: Build & Check for updates
        id: version
        run: |
          go build -o version-updater version-updater.go
          chmod +x ./version-updater
          currenthash=$(md5sum $BURP_VERSION_FILE | cut -d ' ' -f 1)
          ./version-updater > $BURP_VERSION_FILE
          rm -f ./version-updater
          version=$(cat ${{ env.BURP_VERSION_FILE }})
          echo "latest=$version" >> $GITHUB_OUTPUT
          latesthash=$(md5sum $BURP_VERSION_FILE | cut -d ' ' -f 1)
          echo "Updated version hashes: $currenthash to $latesthash"
          if [ "$currenthash" != "$latesthash" ]; then
            echo "### 🚀 New Version - $version" >> $GITHUB_STEP_SUMMARY
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "### Up to date! ($version)" >> $GITHUB_STEP_SUMMARY
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate README.md
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: README.md.j2
          output: README.md
          strict: true
          variables: |
            burp_version=${{ steps.version.outputs.latest }}

      - name: Check Changes
        if: ${{ steps.version.outputs.changes_detected == 'true' }}
        run: |
          echo "Changes detected!"
          echo "Latest version: ${{ steps.version.outputs.latest }}"
          echo "Changes detected: ${{ steps.version.outputs.changes_detected }}"
          cat ${{ env.BURP_VERSION_FILE }}
          git status

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[AUTO] Update Burp Version"
          file_pattern: ${{ env.BURP_VERSION_FILE }} README.md
