name: 🔵 Build Windows

on:
  workflow_call:
    inputs:
      version:
        description: "Version of the application"
        required: true
        type: string

env:
    # Download from https://jdk.java.net/19/
    JDK_URL: https://download.java.net/java/GA/jdk19.0.2/fdb695a9d9064ad6b064dc6df578380c/7/GPL/openjdk-19.0.2_windows-x64_bin.zip
    JDK_VERSION: 19.0.2

jobs:
  build_windows:
    name: Build for Windows
    runs-on: windows-2022
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up prerequisites
        run: |
          cd windows
          7z -h
          $url = 'https://portswigger-cdn.net/burp/releases/download?product=pro&type=Jar&version=${{ inputs.version }}'
          $response = Invoke-WebRequest -Uri $url -UseBasicParsing -Method Head
          $filename = [System.IO.Path]::GetFileName($response.BaseResponse.ResponseUri.LocalPath)
          Invoke-WebRequest -Uri $url -OutFile $filename
          dir