name: 🎉 Release new version

on:
  workflow_run:
    workflows: ["🔄 Check Updates"]
    types:
      - completed
  workflow_dispatch:

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write


jobs:
  release:
    name: Release new version
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GH_USERNAME: github-actions[bot]
      GH_EMAIL: github-actions[bot]@users.noreply.github.com

      # Commit Settings
      #GH_COMMIT_MESSAGE: Version ${{ steps.version.outputs.latest }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
