name: 🔵 Build Windows

on:
  workflow_call:
    inputs:
      version:
        description: "Version of the application"
        required: true
        type: string

jobs:
  build_windows:
    name: Build for Windows
    runs-on: windows-2022
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Download JAR
        run: |
          Invoke-WebRequest -Uri 'https://portswigger-cdn.net/burp/releases/download?product=pro&type=Jar&version=${{ inputs.version }}' -OutFile BurpSuitePro.jar
          dir