name: 🔵 Build Windows

on:
  workflow_call:
    inputs:
      version:
        description: "Version of the application"
        required: true
        type: string

env:
    # Download from https://jdk.java.net/archive/
    JDK_URL: https://download.java.net/java/GA/jdk18.0.2/f6ad4b4450fd4d298113270ec84f30ee/9/GPL/openjdk-18.0.2_windows-x64_bin.zip
    JDK_VERSION: 18.0.2 

jobs:
  build_windows:
    name: Build for Windows
    runs-on: windows-2022
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Set Current Working Directory
        run: |
          cd .\windows\

      - name: Set up JDK
        run: |
          Invoke-WebRequest -Uri '${{ env.JDK_URL }}' -OutFile 'jdk.zip'
          Expand-Archive -Path 'jdk.zip' -DestinationPath '.'
          Remove-Item 'jdk.zip'
          $jdk_dir = (Get-ChildItem "jdk-*")[0].Name
          Move-Item $jdk_dir "jdk"

      - name: Build
        run: |
          $url = 'https://portswigger-cdn.net/burp/releases/download?product=pro&type=Jar&version=${{ inputs.version }}'
          Invoke-WebRequest -OutFile 'burpsuite_pro.jar' -Uri $url
          Invoke-WebRequest -OutFile 'burploader.jar' -Uri 'https://github.com/h3110w0r1d-y/BurpLoaderKeygen/releases/latest/download/BurpLoaderKeygen.jar'
          cmd /c .\make-installer-gh-action.bat .\burpsuite_pro.jar ${{ inputs.version }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: Build/*