name: 🎉 Release new version

on:
  workflow_run:
    workflows: ["🔄 Check Updates"]
    types:
      - completed
  workflow_dispatch:

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write


jobs:
  summary:
    name: Summary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@latest
        with:
          envFilePath: .github/variables/global.env
      
      - name: Download Version Artifact
        uses: actions/download-artifact@v3
        with:
          name: updates
      
      - name: Run ls
        run: |
          ls -la
      
      - name: Print Summary
        run: |
          echo "Latest version: ${{ github.event.workflow_run.outputs.latest }}" >> $GITHUB_STEP_SUMMARY
          echo "Changes detected: ${{ github.event.workflow_run.outputs.changes_detected }}" >> $GITHUB_STEP_SUMMARY
  release:
    name: Release new version
    if: ${{ github.event.workflow_run.outputs.changes_detected == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@latest
        with:
          envFilePath: .github/variables/global.env

#      - name: Download Version Artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: version
#          path: ${{ env.BURP_VERSION_FILE }}

      - run: |
          ls -la
