name: 🔵 Build Windows

on:
  workflow_call:
    inputs:
      version:
        description: "Version of the application"
        required: true
        type: string

env:
    # Download from https://jdk.java.net/archive/ (Win x64 Zip)
    JDK_URL: https://download.java.net/java/GA/jdk21.0.1/415e3f918a1f4062a0074a2794853d0d/12/GPL/openjdk-21.0.1_windows-x64_bin.zip
    JDK_VERSION: 21.0.1

jobs:
  build_installer:
    name: Build Installer for Windows
    runs-on: windows-2022
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build Installer
        run: |
          cd .\windows\

          Invoke-WebRequest -Uri '${{ env.JDK_URL }}' -OutFile 'jdk.zip'
          Expand-Archive -Path 'jdk.zip' -DestinationPath '.'
          Remove-Item 'jdk.zip'
          $jdk_dir = (Get-ChildItem "jdk-*")[0].Name
          Move-Item $jdk_dir "jdk"

          $url = 'https://portswigger-cdn.net/burp/releases/download?product=pro&type=Jar&version=${{ inputs.version }}'
          Invoke-WebRequest -OutFile 'burpsuite_pro.jar' -Uri $url
          Move-Item '..\keygen\BurpLoaderKeygen.jar' 'burploader.jar'

          cmd /c .\make-installer-gh-action.bat .\burpsuite_pro.jar ${{ inputs.version }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: windows/Build/*
            
  build_patcher:
    name: Build Patcher for Windows
    runs-on: windows-2022
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build Patcher
        run: |
          cd .\windows-patcher\
          mkdir Build
          Move-Item '..\keygen\BurpLoaderKeygen.jar' 'burploader.jar'
          cmd /c .\make-patcher-gh-action.bat
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-patcher
          path: windows-patcher/Build/*