name: 🎉 Release new version

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string
      commit_hash:
        description: 'Commit to tag and release'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release_to_github:
    name: Release new version
    needs: [build_windows, build_linux]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@latest
        with:
          envFilePath: .github/variables/global.env

      - name: Download Latest Keygen/Loader
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "h3110w0r1d-y/BurpLoaderKeygen"
          latest: true
          fileName: BurpLoaderKeygen.jar
      
      - name: Release to GitHub
        uses: ncipollo/release-action@v1
        with:
            artifactErrorsFailBuild: true
            artifacts: "BurpLoaderKeygen.jar"
            name: v${{ inputs.version }}
            makeLatest: true
            tag: ${{ inputs.version }}
            commit: ${{ inputs.commit_hash }}
  
  build_windows:
    # Creates a new release if there were changes detected in the previous job.
    # It will also upload the Burp Suite JAR file to the release.
    name: Build Windows
    secrets: inherit
    with:
      version: ${{ inputs.version }}
    uses: mmgordon82/BurpSuiteInstaller/.github/workflows/release-windows.yml@main
  
  build_linux:
    name: Build Linux
    secrets: inherit
    with:
      version: ${{ inputs.version }}
    uses: mmgordon82/BurpSuiteInstaller/.github/workflows/release-linux.yml@main