name: 🟢 Build Linux

on:
  workflow_call:
    inputs:
      version:
        description: "Version of the application"
        required: true
        type: string

jobs:
  build_linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@latest
        with:
          envFilePath: .github/variables/global.env
      
      - name: Download Latest Keygen/Loader
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "h3110w0r1d-y/BurpLoaderKeygen"
          latest: true
          fileName: BurpLoaderKeygen.jar
      
      - name: Build Patcher for Linux
        run: |
          cd linux/
          mkdir archive
          mv ../BurpLoaderKeygen.jar archive/
          mv burp-suite-patch.sh archive/
          wget https://github.com/megastep/makeself/releases/download/release-2.5.0/makeself-2.5.0.run
          chmod +x makeself-2.5.0.run
          ./makeself-2.5.0.run --target .
          ./makeself.sh archive/ BurpSuitePro-Patcher-Linux.sh "Patcher for Burp Suite Pro" ./burp-suite-patch.sh
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.LINUX_ARTIFACT_NAME }}
          path: linux/BurpSuitePro-Patcher-Linux.sh
      
      