name: Tests (dev)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs: 
  create_release:
    # Creates a new release if there were changes detected in the previous job.
    # It will also upload the Burp Suite JAR file to the release.
    name: Create Release
    secrets: inherit
    with:
      version: 2023.3.2
      commit_hash: 443a306eafebf8fbce270515ce132ef417e9722d
    uses: mmgordon82/BurpSuiteInstaller/.github/workflows/release.yml@main
    
          