name: Tests

on:
  workflow_dispatch:

permissions:
  contents: write

jobs: 
  create_release:
    # Creates a new release if there were changes detected in the previous job.
    # It will also upload the Burp Suite JAR file to the release.
    name: Create Release
    secrets: inherit
    with:
      version: 2023.2.3
    uses: mmgordon82/BurpSuiteInstaller/.github/workflows/release.yml@main
    
          