name: Tests (dev)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs: 
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Run commands
        run: |
          echo "Running tests..."
          echo "Latest Release (via curl): $(curl -s https://api.github.com/repos/${{ github.repository}}/releases/latest | jq -r .tag_name)"
          echo "Latest Release (via git): $(git describe --tags)"
          echo "Tests passed!"